---
all:
  children:
    proxmox:
      children:
        dev:
          hosts:
            pve-dev-01:
              ansible_host: 192.168.1.20  # Update with actual IP
            # pve-dev-02:
            #   ansible_host: 192.168.1.21
